version: 2.1

executors:
  ubuntu-executor:
    docker:
      - image: cimg/base:stable
    working_directory: ~/project

parameters:
  target:
    type: string
    default: "r9q"

jobs:
  build:
    executor: ubuntu-executor
    parameters:
      target:
        type: string
    environment:
      PLATFORM_KEY_PK8: << pipeline.parameters.PLATFORM_KEY_PK8 >>
      PLATFORM_KEY_PEM: << pipeline.parameters.PLATFORM_KEY_PEM >>
      GOFILE_TOKEN: << pipeline.parameters.GOFILE_TOKEN >>
      GOFILE_FOLDER_ID: << pipeline.parameters.GOFILE_FOLDER_ID >>
    steps:
      - checkout:
          path: ~/project

      - run:
          name: Free disk space (1/3)
          command: |
            sudo rm -rf /usr/share/dotnet /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL
            sudo docker image prune --all --force
            sudo docker builder prune -a

      - run:
          name: Free disk space (2/3)
          command: |
            echo "Simulating jlumbroso/free-disk-space@main"
            # Add equivalent cleanup commands here if needed

      - run:
          name: Free disk space (3/3)
          command: |
            echo "Simulating rokibhasansagar/slimhub_actions@main"
            # Add equivalent cleanup commands here if needed

      - run:
          name: Set up build environment
          command: |
            sudo apt update
            DEBIAN_FRONTEND=noninteractive sudo apt install -yq \
              p7zip-full jq attr ccache clang ffmpeg golang \
              libbrotli-dev libgtest-dev libprotobuf-dev libunwind-dev libpcre2-dev \
              libzstd-dev linux-modules-extra-$(uname -r) lld protobuf-compiler webp \
              curl xxd patchelf flex bison libarchive-tools build-essential pcre2-utils
            sudo modprobe erofs f2fs
            git config --global user.name "circleci"
            git config --global user.email "circleci@localhost"
            echo -n "$PLATFORM_KEY_PK8" | base64 --decode > security/extremerom_platform.pk8
            echo -n "$PLATFORM_KEY_PEM" | base64 --decode > security/extremerom_platform.x509.pem

      - run:
          name: Set up JDK 11
          command: |
            sudo apt install -y openjdk-11-jdk
            export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
            export PATH=$JAVA_HOME/bin:$PATH

      - run:
          name: Build dependencies
          command: |
            source ./buildenv.sh << parameters.target >>
            ./scripts/build_dependencies.sh

      - run:
          name: Download source firmware
          command: |
            source ./buildenv.sh << parameters.target >>
            ./scripts/download_fw.sh --force --ignore-target

      - run:
          name: Extract source firmware
          command: |
            source ./buildenv.sh << parameters.target >>
            ./scripts/extract_fw.sh --force --ignore-target

      - run:
          name: Download target firmware
          command: |
            source ./buildenv.sh << parameters.target >>
            ./scripts/download_fw.sh --force --ignore-source

      - run:
          name: Extract target firmware
          command: |
            source ./buildenv.sh << parameters.target >>
            ./scripts/extract_fw.sh --force --ignore-source

      - run:
          name: Build ROM
          command: |
            source ./buildenv.sh << parameters.target >>
            ./scripts/make_rom.sh --force

      - run:
          name: Upload to GoFile
          command: |
            ZIP_FILE=$(find out -maxdepth 1 -type f -name "*.zip" | head -n 1)
            RESPONSE=$(curl -s -F "file=@$ZIP_FILE" -F "token=$GOFILE_TOKEN" -F "folderId=$GOFILE_FOLDER_ID" "https://upload-eu-par.gofile.io/uploadFile")
            echo "Uploaded successfully! Download link:"
            echo "$RESPONSE" | jq -r '.data.downloadPage'
            echo "MD5:"
            md5sum "$ZIP_FILE"
            echo "SHA256:"
            sha256sum "$ZIP_FILE"

workflows:
  build_extremerom:
    jobs:
      - build:
          matrix:
            parameters:
              target: ["r9q", "r9q2"]

